name: mime
version: 0.9.6+3

description: Helper-package for working with MIME.
author: Dart Team <misc@dartlang.org>
homepage: https://www.github.com/dart-lang/mime

environment:
  sdk: '>=2.0.0-dev.20.0 <3.0.0'

dev_dependencies:
  test: ^1.2.0
